### ISSUE TITLE
Test favicons loaded by <link rel="icon" href="..." />

### ISSUE THREAD

**Issue by arichiv** [arthuredelstein/privacytests.org#130]
In Chrome favicons loaded via a link tag go in a different cache than the general http resource cache. I recently fixed an [issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1300214) in Chrome which allowed cross-origin history sniffing, and it might be worth testing here as well. Let me know if I misunderstand the underlying [favicon test](https://github.com/arthuredelstein/privacytests.org/blob/6bc744aa71d94d3d01c5295e94b66cdb66157d64/static/test_definitions.js#L230) currently used.

**Comment by arthuredelstein** [comment]
Hi Ari -- thank you so much for letting me know! Indeed the latest published test results shows that favicons are indeed now partitioned in Chrome Canary (107.0): https://privacytests.org/nightly.html

And this result is new since Chrome Canary 106.0 a couple of weeks before: https://privacytests.org/archive/issue30/nightly.html

Once Chrome 106 reaches Stable, this will be visible on the main page as well.

Thanks again for getting in touch and for this awesome work! [🥳](https://emojipedia.org/partying-face/)
